name: pBun.github.io
description: dustin boersma | front-end web developer
author:
  name: Dustin Boersma
  email: dustin.boersma@gmail.com

exclude: ['_source', 'package.json', 'node_modules', 'gulpfile.js']
include: ['.htaccess']
markdown: redcarpet
highlighter: 'rouge'
safe: true
lsi: false
