title: Dustin Boersma
description: Hello, my name is Dustin Boersma. I'm a web developer, and I specialize in front-end and visual problem solving.
author:
  name: Dustin Boersma
sass:
  style: compressed
